### ISSUE TITLE
Complete the PR #126 and change method "generateRandomPassword" in class Password

### ISSUE THREAD

**Issue by mpolitano** [saiema/ProgramRepairGolf-DOSE2019#135]
This issues was created for resolve the comments in PR  #126 assigned to @alejandrobarrios 

-[] Change the method generateRandomPassword for some more simply

**Comment by alejandrobarrios** [comment]
I participate in this issue.

**Comment by alejandrobarrios** [comment]
this issue it has already been result in the pull request #145.

**Comment by alejandrobarrios** [comment]
@mpolitano this issue has been already resolved.
