### ISSUE TITLE
User Sign Up 

### ISSUE THREAD

**Issue by alejandrobarrios** [saiema/ProgramRepairGolf-DOSE2019#39]
- [x] Create a method that allows to sign up a user.

- [x] Create test that try this function.

Belongs to User functionalities

This issue is for create the functionality that allows a user to create an account with asking him a username, a password and a email_address. This functionality must save the data entered by the user, if username is not used for other user. And returns a message saying "User created successfully" ,if data is save, or a message saying "Username is already used" ,if can not load the date entered by the user.

**Comment by valetobares11** [comment]
I also participate in this issue

**Comment by maxigaspero** [comment]
I also participate in this issue
