### ISSUE TITLE
User Reset Password 

### ISSUE THREAD

**Issue by valetobares11** [saiema/ProgramRepairGolf-DOSE2019#44]
- [ ] Create method for Reset Password a User. 

- [ ] Create test that try this function.

Belongs to User functionalities.

This issue is created to modify the password of a user who is already registered.You will be asked for a new password and it will be modified, in case the modification is made you will be returned a message that the password has been modified successfully, otherwise an error message.

**Comment by alejandrobarrios** [comment]
I also participate in this issue

**Comment by maxigaspero** [comment]
I also participate in this issue

**Comment by valetobares11** [comment]
this edition has already been resolved
