### ISSUE TITLE
User log In

### ISSUE THREAD

**Issue by maxigaspero** [saiema/ProgramRepairGolf-DOSE2019#48]
- [x] Create method for allow a user login in the system

- [x] Create unit Test

Belong to User funcionalities

This issue is for create the method with enable a user get into the system. The validation it wil be use the username and password. If validation is correct, then the use will be inside the system.  Use funcionality search User.

**Comment by alejandrobarrios** [comment]
I also participate in this issue

**Comment by valetobares11** [comment]
I also participate in this issue

**Comment by maxigaspero** [comment]
This issue was resolved
