### ISSUE TITLE
Create response 

### ISSUE THREAD

**Issue by EriGoldenberg** [saiema/ProgramRepairGolf-DOSE2019#49]
- [ ] Create a method that receives a description, comment id, and a user as parameters and saves the response (as a comment) 

- [ ] Test creation for the method performed.

This issue belongs to comment functionalities.
(The title and the challenge_id will be obtained by the comment which it references )

**Comment by yani-c** [comment]
Yo

**Comment by hernan-dp** [comment]
yo tambien
