### ISSUE TITLE
Update User Data

### ISSUE THREAD

**Issue by valetobares11** [saiema/ProgramRepairGolf-DOSE2019#50]
- [ ] Create method for Update User Data. 

- [ ] Create test that try this function.

Belongs to User functionalities.

This issue is created to modify the data of the registered user.You will be asked for the information that the user wishes to update, once updated, a message will be sent telling you that the account details have been updated successfully. If they cannot be updated, an error message will be sent.

**Comment by maxigaspero** [comment]
I also participate in this issue

**Comment by valetobares11** [comment]
this edition has already been resolved
