### ISSUE TITLE
Create view comment

### ISSUE THREAD

**Issue by EriGoldenberg** [saiema/ProgramRepairGolf-DOSE2019#52]
- [ ] Create a method that receives as parameters an id and an object (for example user, challenge) and list comments depending on the object with that id.

- [ ] Test creation for the method performed.

This issue belongs to comment functionalities.
(The object passed as parameter in the method refers to what comment attribute the id refers to, for example if the object passed is a user, the id refers to 'user_id' attribute).

**Comment by yani-c** [comment]
Yo

**Comment by hernan-dp** [comment]
yo tambien
