### ISSUE TITLE
Create compilation challenge

### ISSUE THREAD

**Issue by cuestalvaro** [saiema/ProgramRepairGolf-DOSE2019#70]
- [x] create compilation challenge model

- [x] create compilation challenge table

- [x] create method to create challenge

- [x] validate compilation challenge

- [x] create test for creation method

This issue is about providing the functionalities so that the administrator user can create compilation challenges. The tasks to be implemented are to create a table in the database to store it, creating a model that allows us to manipulate the attributes and functionalities. In addition, a method that allows us to load the challenge into the database must be validated before loading (the program must not compile). Finally a test for the functionality described above.

**Comment by brusatimatias** [comment]
.
